---
# k get sa deployer -o yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployer
  namespace: dev-ns
# secrets:
# - name: deployer-token-ltznb
---
# k get clusterrole system:deployer -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:deployer
rules:
- apiGroups:
  - ""
  resources:
  - replicationcontrollers
  verbs:
  - delete
- apiGroups:
  - ""
  resources:
  - replicationcontrollers
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - replicationcontrollers/scale
  verbs:
  - get
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - list
- apiGroups:
  - ""
  - image.openshift.io
  resources:
  - imagestreamtags
  - imagetags
  verbs:
  - create
  - update

---
# k get rolebinding system:deployers -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:deployers
  namespace: dev-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:deployer
subjects:
- kind: ServiceAccount
  name: deployer
  namespace: dev-ns

